parse_api_contract:
  description: >
    Parse and carefully analyze the provided OpenAPI 3.0 contract and extract all the necessary details to define the implementation requirements. 
    Break these requirements down into clear tasks for building the Controller, Service, and Repository layers, along with all the data models needed for each API. 
    Organize this information systematically by API tags to ensure every aspect is addressed.
    Ensure the tasks include:
    - Clear definitions for all API endpoints, request and response payloads.
    - Data models with appropriate fields, types, and validation rules.
    - Database schema design, including relationships and constraints.
    - Service methods with defined business logic and exception handling.
    - Comprehensive security considerations, including authentication and input validation.
    Please incorporate the following feedback if present:
    (feedback)
  expected_output: >
    Complete and Detailed tasks for each layer, including all endpoint details, all data models, all database schema, and all service methods. This output will be organized by API tags for clarity and completeness.
  agent: tech_lead