parse_api_contract: 
  description: >
    Parse and thoroughly analyze the provided OpenAPI 3.0 contract to extract comprehensive details for Spring Boot application development.
    Break down the requirements into actionable tasks for the following layers: Controller, Service, and Repository, including all necessary data models.
    Ensure a systematic and organized approach by categorizing tasks by API tags.
    Include the following critical aspects:
    - Clear and complete definitions for all API endpoints, request and response payloads, and HTTP methods.
    - Detailed specifications for data models, including field definitions, data types, validation rules, and relationships.
    - Database schema design, covering relationships, constraints, and indexing.
    - Service methods with defined business logic, exception handling, and input/output validation.
    - Comprehensive security considerations such as authentication, authorization, and input sanitization.
    - Thorough logging and monitoring strategies for all API operations.
    Please incorporate the following feedback if present:
    {feedback}
  expected_output: >
    A well-organized, detailed set of tasks to build a fully functional Spring Boot application from the parsed API contract.
    This includes:
    - Fully defined endpoint specifications.
    - Comprehensive data models and database schema.
    - Defined service methods with business logic and exception handling.
    - Tasks categorized by API tags for clarity and completeness.
  agent: tech_lead
