evalute_api_task:
  description: >
    Carefully analyze the provided OpenAPI 3.0 contract and verify the given API contract meets strict guidelines for Spring Boot applications. 
    Ensure the following criteria are met:
    - Complete data model coverage with appropriate validation annotations and relationships.
    - Comprehensive endpoint specifications, following RESTful conventions and proper HTTP methods.
    - Detailed request and response structures, including mandatory fields and status codes.
    - Complete service method mapping with correct exception handling and separation of concerns.
    - Comprehensive API documentation with Swagger/OpenAPI, clear descriptions, and versioning.
    - Security evaluation ensuring authentication, secure communication protocols, input validation, and secure headers.

    Your final response must include:
    Valid: True/False
    Feedback: Provide commentary if the post fails any of the criteria.
    API contract to Verify:
    {api_result}
  expected_output: >
    Pass: True/False
    Feedback: Provide commentary if the contract fails any of the criteria.
  agent: evalute_api
