generate_service_layer:
  description: >
    Extract relavent information from  {api_result} to generate the service layer for the Spring Boot application.
    Based on the provided API contract, create a fully functional service layer with the following steps:
    - Identify all required service classes from {api_result} and generate corresponding Java classes.
    - Implement methods in each service class based on the API endpoints and required business logic extracted from {api_result}.
    - Ensure each service class interacts with its respective repository and model layer.
    - Use `@Service` annotation for each service class and `@Transactional` where needed.
    - Follow best practices for dependency injection using `@Autowired` or constructor injection.
    - Validate the generated service classes against the API contract to ensure all required methods are implemented.

  expected_output: >
    Java service class files dynamically generated based on {api_result}, ensuring proper handling of business logic.
    - The generated files should be placed in the existing boilerplate folder structure at {folder_path}.
    - If there is no folder at {folder_path}, create a `service` folder in the same path and place the generated files inside.
    - Ensure service methods align with the parsed API contract, maintaining best practices in Spring Boot.
